### ISSUE TITLE
3 Force closures and pending balances from HODL Invoices (Robosats)

### ISSUE THREAD

**Issue by lescuer97** [MutinyWallet/mutiny-web#805]
I suddendly got 3 channel force closures in which I also had some HODL invoices with those channels so I actually don't know the state in which they are now.

NOTE: Both HODL invoices should at the en not have been payed out and returned to me. 

Another problem that I have is that a lot of time I can't see my **Activity** list as it bugs out:

LOGS:
[mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-node/files/13839971/mutiny-logs.txt)

UI Bugs Issue:

![signal-2024-01-05-095729_004](https://github.com/MutinyWallet/mutiny-node/assets/47948594/ee6458d6-c817-4c21-81e9-e5f840aadec8)
![signal-2024-01-05-095729_003](https://github.com/MutinyWallet/mutiny-node/assets/47948594/d61b30c5-b502-4845-9def-9022ba1d7cb3)

**Comment by TonyGiorgio** [comment]
We just pushed an update, I wonder if it helps things at all here.

**Comment by lescuer97** [comment]
> We just pushed an update, I wonder if it helps things at all here.

it would help on seeing the transactions better or less probability of force closures?

**Comment by TonyGiorgio** [comment]
> > We just pushed an update, I wonder if it helps things at all here.
> 
> it would help on seeing the transactions better or less probability of force closures?

Well we just pushed an update that would hopefully load things properly to help you see them. I'm guessing you're saying that didn't work?

**Comment by lescuer97** [comment]
> > > We just pushed an update, I wonder if it helps things at all here.
> > 
> > 
> > it would help on seeing the transactions better or less probability of force closures?
> 
> Well we just pushed an update that would hopefully load things properly to help you see them. I'm guessing you're saying that didn't work?

okok for some reason Obtanium had not given me the update.

 I'm able to see a channel that I could not see before. Previous version the Channels page was always empty (had not checked it until the force closures)

I weirdly still have a pending payment but that could absolutely be Robosats holding the payment for some reason (it has been pending for more then 2 weeks).  

btw is there a way to get in the fedimint beta?

**Comment by TonyGiorgio** [comment]
Sometimes the pending transactions exist longer than they should and never go away. It's hard to tell. 

But hodl invoices are VERY susceptible to force closes especially when you use a self custodial mobile wallet. 

I do agree, we have an open issue for getting the TXID and we're waiting for an LDK update to allow us to get that. 

We don't have any fedimint invite codes to give out but I'd imagine they start popping up soon. It is now available for people to set up and run.
